### ISSUE TITLE
Exception thrown when default language is english, us.

### ISSUE THREAD

**Issue by ghost** [polincdev/MenuTemplate#1]
If the default language is English, US, an exception is thrown when one tries to run the project with this error message:  "MissingResourceException: Can't find bundle for base name Bundle_en, locale en_US"

**Comment by polincdev** [comment]
Hi. Unfortunately the project structure is a little bit messy. It is a result of combining SDK/NetBeans, Maven/Gradle and java internationalization project structures. It is like that only for the sake of JMonkeystore. I can assure you that the project runs properly and file Bundle_en.properties is in place. The thing is in the end it should be placed next to the top source folder - originally org. But with the Maven structure it is next to main.java.org. I don't know how you build your projects but in production you must place all the Bundle language properties directly next to the top folder i.e. org or main.

**Comment by ghost** [comment]
Ok, is "it" the bundle? I copy all the files directly from the source into a new jme project. I do all this in the official SDK

**Comment by polincdev** [comment]
Because other people also complained about this project structure  I reverted it to the NetBeans project. Now it is a plain SDK project that will run out of the box if you copy it into the SDK.

**Comment by ghost** [comment]
OK thanks! It is working now, great contribution to jME!
